version: '3'
services:
    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mqtt
        ports:
            - "1883:1883"
        restart: always

    postgres:
        image: "postgres:11-alpine"
        container_name: farmr-postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: farmr
            POSTGRES_USER: farmr
            POSTGRES_PASSWORD: hotfarmr69

    api:
        build: ./flask/
        container_name: farmer-api
        volumes:
        - "./flask:/app"
        depends_on:
        - postgres
        ports:
        - "5000:5000"
        environment:
        - FLASK_ENV=development
        - DATABASE_URL=postgresql://orderwrite:orderwrite@postgres/orderwrite
        command: >
            bash -c "flask drop &&
                    flask db upgrade &&
                    flask seed &&
                    flask run --reload --host=0.0.0.0"

    # bridge:
    #     build: ./bridge/
    #     container_name: bridge
    #     depends_on:
    #         - influxdb
    #         - postgres
    #     command: python bridge.py
